### ISSUE TITLE
Exclusive range

### ISSUE THREAD

**Issue by v-kolesnikov** [inkarkat/vim-SyntaxRange#1]
Hi!
I have the following Ruby code: 

```ruby
    query = <<~SQL.split("\n").map(&:strip).join(' ')
      SELECT * from users;
    SQL
```

where I would like highlight section between `<<~SQL` and `SQL` statements. I wrote next patterns in my config: `au FileType ruby call SyntaxRange#Include('<<\~SQL', 'SQL', 'sql')`, but it capture all this section inclusive with both statements. How I can make it not inclusive?

**Comment by inkarkat** [comment]
The SyntaxRange plugin basically just provides syntactic sugar for the built-in `:syntax include` and `:syntax region` commands.

If you want to exclude the remainder of the line that starts the Ruby here-doc, the regular expression for the start of the region has to be tweaked. This can be done by switching from `SyntaxRange#Include()` to the more powerful `SyntaxRange#IncludeEx()` variant:

    call SyntaxRange#IncludeEx('keepend start="\%(<<\~SQL\>.*\n\)\@<=" end="SQL" containedin=ALL', 'sql')

The pattern asserts the here-doc start at the previous line (via _positive lookbehind_ `\@<=`); the actual match only starts at the beginning of the first here-doc line (containing SQL). With this, the here-doc start will still be parsed as Ruby code.

**Comment by v-kolesnikov** [comment]
Thanks a lot!
