### ISSUE TITLE
How can I add a line offset to {startPattern} and {EndPattern} in SyntaxRange#Include(...)?

### ISSUE THREAD

**Issue by kiryph** [inkarkat/vim-SyntaxRange#15]
I have a yaml file with [string blocks](https://yaml.org/spec/1.2.2/#example-indentation-determines-scope) which I want to highlight as shell scripts:
```yaml
...
      - shortcut_name: "Up in Stack"
        shortcut_modifier: *mod_focus
        shortcut_key: *previnstack
        shortcut_cmd: |
          yabai -m window --focus stack.prev \
          || yabai -m window --focus stack.last
      - shortcut_name: "Down in Stack"
        shortcut_modifier: *mod_focus
        shortcut_key: *nextinstack
        shortcut_cmd: |
          yabai -m window --focus stack.next \
          || yabai -m window --focus stack.first
      - shortcut_name: "Left Space"
        shortcut_fullname: "Left Space"
        shortcut_modifier: *mod_focus
        shortcut_key: *prevspace
        shortcut_cmd: |
          SPACE_SET_PRIMARY_OFFSET=1;\
          SPACE_IDX=$(yabai -m query --spaces --space | jq '.index');\
          DISPLAY_IDX=$(yabai -m query --displays --display | jq '.index');\
          IS_PRIMARY=$(yabai -m query --displays --display | jq 'if .frame.x == 0.0 and .frame.y == 0.0 then 0 else 1 end');\
          DISPLAY_CNT=$(yabai -m query --displays | jq 'length');\
          SPACE_SET_CNT=$(yabai -m query --spaces --display | jq 'length');\
          if [ "$IS_PRIMARY" -eq "0" ] ; then\
            SPACE_SET_CNT=$((SPACE_SET_CNT-1));\
          fi;\
      - shortcut_name: "Right Space"
...
```
`:call SyntaxRange#Include('shortcut_cmd', 'shortcut_name', 'zsh')`

This gives me

![Screenshot 2022-07-24 at 10 19 40](https://user-images.githubusercontent.com/371756/180638611-bc8dee35-4f39-44f4-83aa-b9fb5e21c239.png)

As you can see the lines with StartPattern and EndPattern also change the syntax highlighting which I do not want. Can I add an offset to the patterns, e.g. following `:help syn-pattern-offset`?

`:call SyntaxRange#Include('/shortcut_cmd: |/rs=e', '/shortcut_name/re=s', 'zsh')`

**Update** improved `{EndPattern}`: `[^\\|]$` (search for first line ending which does not end with `\` or `|`) But the `{StartPattern}` could benefit from a possible offset

`:call SyntaxRange#Include('shortcut_cmd', '[^\\|]$', 'zsh')`

![Screenshot 2022-07-24 at 10 33 18](https://user-images.githubusercontent.com/371756/180639142-59d97e74-bc27-4c91-910c-cbe6fc29501f.png)

Related question: https://vi.stackexchange.com/questions/13062/exclude-start-and-end-match-from-region

**Comment by inkarkat** [comment]
`SyntaxRange#Include()` covers the common case of simple start and end markers.

To have full control over the syntax region (and apply a _syntax pattern offset_), use `SyntaxRange#IncludeEx()` instead. Instead of separate `{startPattern}` and `{endPattern}` argument, this takes one `{regionDefinition}` argument, where you supply the `[matchgroup=...] start=... [skip=...] end=...` yourself.

**Comment by kiryph** [comment]
Thanks for pointing `SyntaxRange#IncludeEx(...)` out.

Following customized region does the job:

```VimL
call SyntaxRange#IncludeEx('matchgroup=yamlBlockMappingKey keepend start="shortcut_cmd: |" end="[^\\|]$"re=e containedin=ALL', 'zsh')
```
![Screenshot 2022-07-24 at 15 27 57](https://user-images.githubusercontent.com/371756/180649178-0be10810-6c76-4ede-bc1f-697ea75edb61.png)
