### ISSUE TITLE
Compatibility with nvim-treesitter module highlight

### ISSUE THREAD

**Issue by kiryph** [inkarkat/vim-SyntaxRange#16]
I am using neovim with [nvim-treesitter highlight](https://github.com/nvim-treesitter/nvim-treesitter#highlight).

I noticed that vim-SyntaxRange is not compatible with nvim-treesitter highlight. I had to disable nvim-treesitter highlight with `:TSDisable highlight`.

Can this be improved?

**Comment by inkarkat** [comment]
I'm not using Neovim nor that plugin, but if someone contributes some smaller tweaks that improve compatibility (*), I'm certainly open to include such.

* Note that this plugin itself is just a thin convenience wrapper around Vim's `:syntax include`, and therefore is tightly bound to that core functionality.

**Comment by kiryph** [comment]
> Note that this plugin itself is just a thin convenience wrapper around Vim's :syntax include, and therefore is tightly bound to that core functionality.

I have now a better understanding of this vim plugin and I agree that compatibility with treesitter syntax highlighting does not fit into. If treesitter allows a simple on demand syntax highlighting for ranges, someone could write a neovim treesitter plugin.
