### ISSUE TITLE
Trying to use `SyntaxRange` in SpaceVim

### ISSUE THREAD

**Issue by fpom** [inkarkat/vim-SyntaxRange#17]
I want to be able to use `SyntaxRange` in `SpaceVim`, but I only partially succeeded. I've made a [feature request to `SpaceVim`](https://github.com/SpaceVim/SpaceVim/issues/4800) since, presumably, I'm not correctly using their configuration system. But I wanted to let you know about this in case you have a solution.

**Comment by inkarkat** [comment]
Other than having heard the name, I have absolutely no experience with SpaceVim, nor am I a fan of Vim "distributions". But as long as there's a real Vim core underneath those additional conventions and abstractions (that seem to be causing the problem), the SyntaxRange plugin should work there, too, as it's only a thin convenience wrapper around `:syntax include`.
