### ISSUE TITLE
Embedded syntax stopped working

### ISSUE THREAD

**Issue by bpj** [inkarkat/vim-SyntaxRange#18]
**Describe the bug**

_A clear and concise description of what the bug is._

Embedded highlighting through `call SyntaxRange#include(....)` in a `~/.vim/after/syntax/<filetype>/SyntaxInclude.vim` file suddenly stopped working. The matchgroup highlighting works as expected, and the surrounding language's highlighting is overridden but the body of the region isn't highlighted at all.

**How to Reproduce**

_Detailed steps to reproduce the behavior._

I don't know because TTBOMK I haven't changed anything in my setup. There is a remote possibility that my package manager has updated Vim behind my back because some other package listed Vim as a dependency but if so that was some weeks ago and I first ran into this only days ago.
Probably I inadvertently changed some option, but which?
FWIW setting the syntax for the entire file to the embedded syntax works.

**Expected Behavior**

_A clear and concise description of what you expected to happen._

Both the matchgroup/delimiters and the delimited range to be highlighted. The latter isn't.

**Environment**
 - Plugin version (e.g. stable version _1.10_) / revision _a1b2c3d4_ from the master branch

Not sure where to find it grepped the repo for -i version no relevant hit

git tag says 1.03

The top entry in git log says

``````commit 3a7fd9ff50fabafe61df12522ed2f275c8e2f45e (HEAD -> master, origin/master, origin/HEAD)
Author: Ingo Karkat <swdev@ingo-karkat.de>
Date:   Sat Jan 16 19:31:21 2021 +0100
``````

 - Dependency versions (e.g. [ingo-library plugin](https://github.com/inkarkat/vim-ingo-library), or external tool versions)

vim-ingo-library git tag says 1.044

git log top entry says

``````
commit 097b1c729ee0f334a40eddfbd84d77161287f2f1 (HEAD -> master, origin/master, origin/HEAD)
Merge: 461680f ec21111
Author: Ingo Karkat <swdev@ingo-karkat.de>
Date:   Fri Dec 30 15:34:16 2022 +0100
``````

 - Vim version (e.g. _8.1.1234_) Or paste the result of `vim --version`.

``````
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Feb 24 2023 20:06:18)
Included patches: 1-1350
Compiled by builder@cde1dec5ce2f
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            -netbeans_intg     +termresponse
+balloon_eval_term -gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/data/data/com.termux/files/usr/share/vim"
Compilation: aarch64-linux-android-clang -c -I. -Iproto -DHAVE_CONFIG_H -I/data/data/com.termux/files/usr/include -fstack-protector-strong -Oz -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: aarch64-linux-android-clang -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -o vim -lm -lncursesw -liconv -L/data/data/com.termux/files/usr/lib/python3.11/config-3.11/ -lpython3.11 -ldl -lpthread -lm 

``````

 - OS: (e.g. _Ubuntu 18.04_, _Windows 10 1809_, _macOS 10.14_)

Termux 0.118.0 under Android/Samsung (not sure which Android version. I did an Android update some time before this started, but it looks like a pure Vim issue.)

 - Install method: (e.g. manually via Vimball or ZIP file, GitHub clone as pack plugin, Plugin manager _NAME_)

GitHub clone/pathogen

 - Other plugins / additional context if you think this could be important

**Comment by inkarkat** [comment]
The general syntax include mechanism is still working for me (Vim 9.0.1591), the problem likely is related to the syntax used. Maybe a new syntax plugin version got picked up and that one is the root cause?!

**Comment by bpj** [comment]
Do you mean a syntax plugin for a specific filetype/syntax? Could be. It seems to happen only with a specific host syntax, namely MoonScript. I found that if I remove my syntax/moon/SyntaxInclude.vim and define the region in `~/.vim/after/syntax/moon.vim` using the pattern described in `:h :syn-include` it works. It does not work if I use `:SyntaxInclude {filetype}` either but that's hardly a surprise.

**Comment by bpj** [comment]
I also found that with the regularly defined region synIDattr() reports 'name' to be the name of the group from the included syntax, but if I use the plugin with non-working highlighting I get a name `SyntaxInclude{Filetype}`. This reminds me that I've had problems with nested included syntaxes (under termux) before. Could it be that?

**Comment by inkarkat** [comment]
>  if I remove my syntax/moon/SyntaxInclude.vim and define the region in ~/.vim/after/syntax/moon.vim using the pattern described in :h :syn-include it works

Well, the plugin basically is just syntactic sugar around `:syn include`, so if you get it to work manually, the plugin should be able to do it as well (but with a more comfortable definition).

> I've had problems with nested included syntaxes

Oh, that's interesting; my uses have been rather straightforward (like embedding diffs in email content). Again, anything that a sequence of `:syntax include` commands can do should be possible with the plugin as well.

**Comment by bpj** [comment]
Found it! The cause was one of two things, or possibly both:

1.  Relative paths in `:syn include` seem to be unreliable under Termux due to Android's unorthodox file system structure. I had to prefix `$HOME/.vim/` or `$VIMRUNTIME/` as the case may be.
2. There was a case of circular inclusion. Your plugin apparently bailed out while my manual inclusions were thrown into an infinite loop. I had to save/`unlet`/`let` some global variables the included syntax used to configure its includes before/after my manual include.

At least I think that is what happened since things now work after reimplementing all my includes manually.

Feel free to close this unless you want to investigate further. Am I correct that the plugin manages to bail out if there is a circular include, or is that just a side effect of `eval()`? If it can catch it maybe it should throw an error if it does?

**Comment by inkarkat** [comment]
Ah, great! Yes, the plugin maintains a list of included filetypes in `b:SyntaxRange_Included.filetypes` and silently skips the `:syn include` if it has already been included. The intention is to support complex syntax relationships; throwing an error might have helped in your case, but generally would be counterproductive.

Relative paths are the recommended way, as it transparently handles syntax plugin sources anywhere in the `'runtimepath'`. That _should_ also work with unorthodox paths (as long as they don't change during Vim's lifetime).

Thanks for looking into this and reporting back; this might help other users in the future. Happy Vimming!

**Comment by bpj** [comment]
> Relative paths are the recommended way, as it transparently handles syntax plugin sources anywhere in the 'runtimepath'. That should also work with unorthodox paths (as long as they don't change during Vim's lifetime).

I know, but sometimes they Just Don't Work under Termux. I have no idea why, but I *think* Termux does some magic in order to make orthodox-looking paths work.
