### ISSUE TITLE
Work on highlighted region

### ISSUE THREAD

**Issue by HaleTom** [inkarkat/vim-SyntaxRange#2]
Is / would it be possible to be able to highlight a region and then set the syntax highlighting only for the highlight?

**Comment by inkarkat** [comment]
The `:SyntaxInclude` command is line-based, but you can achieve that with `:call SyntaxRange#Include( {startPattern}, {endPattern}, {filetype} [, {matchGroup} [, {contains}]] )`).

Your use of _highlight_ is a bit confusing; to clarify, the syntax would apply to all text within `{startPattern}` up to `{endPattern}`. As with `:syntax region`, you can define a separate highlighting for the pattern matches itself via `{matchGroup}`.
