### ISSUE TITLE
Syntax highlight markdown formulas using LaTeX highlighting

### ISSUE THREAD

**Issue by HaleTom** [inkarkat/vim-SyntaxRange#3]
Thanks for this plugin! I hope that it can solve a question that I raised on [vi.stackexchange](https://vi.stackexchange.com/q/16376/5324):

--------------

I often write non-trivial mathematical formulas inside Markdown documents, and having them syntax-highlighted would really help.

In Markdown, LaTeX math formulae are denoted:
`$x^2$` and `$$x^2$$`, and are escaped as `\$x\$ `and `\$\$x\$\$`.

Markdown math formulas are rendered via MathJax (to match future googlers' keywords).

If I use [vim-markdown](https://github.com/plasticboy/vim-markdown) to syntax highlight the Markdown, how can I use [vimtex](https://github.com/lervag/vimtex) to syntax highlight only the text inside the formulae?

**Note:** I only want the text inside `$` to be treated differently if the filetype is `markdown` or `foobar` (future proofing against my lack of VimL).

**Bonus:** I'd like the `$` delimiters themselves to use the syntax highlight group `Statement`.

**Hints:** 

I think these are along the right path, but I couldn't work out how the solution from them:

* Perhaps [vim-SyntaxRange](https://github.com/inkarkat/vim-SyntaxRange) would help. (I couldn't work out how to set it up with the delimiters.) I would prefer a solution which didn't require an extra plugin if possible though.
* vim wikia's [Different syntax highlighting within regions of a file](http://vim.wikia.com/wiki/Different_syntax_highlighting_within_regions_of_a_file)
* [This code](https://stsievert.com/blog/2016/01/06/vim-jekyll-mathjax/):

        " Block math. Look for "$$[anything]$$"
        syn region math start=/\$\$/ end=/\$\$/
        " Inline math. Look for "$[not $][anything]$"
        syn match math_block '\$[^$].\{-}\$'

-------

I thought that this was quite a common use case for your plugin, and you may wish to gain some advertising potential by answering the [vi.stackexchange question]( [vi.stackexchange](https://vi.stackexchange.com/q/16376/5324):
). 😃

**Comment by Konfekt** [comment]
To highlight math formulas in markdown, there is https://github.com/vim-pandoc/vim-pandoc-syntax .

**Comment by inkarkat** [comment]
I don't think you need my plugin for that, as the _vim-markdown_ plugin can optionally include the _tex_ syntax on its own. If it weren't, you could of course use _SyntaxRange_ for it.

**Comment by HaleTom** [comment]
@inkarkat I've tried using `vim-markdown` with `g:vim_markdown_math = 1`.  I see both the formula and fencing `$` as uncoloured.
