### ISSUE TITLE
Error detected while processing function SyntaxRange#SyntaxInclude

### ISSUE THREAD

**Issue by HaleTom** [inkarkat/vim-SyntaxRange#4]
If I have a line of text:

```
 \frac a^{ab} b
```

and highlight it, then type:

```
:'<,'>SyntaxInclude tex
```

I see:

```
Error detected while processing function SyntaxRange#SyntaxInclude:
line    1:
E117: Unknown function: ingo#range#NetStart
E15: Invalid expression: [ingo#range#NetStart(a:startLnum), ingo#range#NetEnd(a:endLnum)]
line    2:
E121: Undefined variable: l:startLnum
E116: Invalid arguments for function printf
E116: Invalid arguments for function SyntaxRange#Include
Press ENTER or type command to continue
```

**Comment by HaleTom** [comment]
Sorry, I just saw your reply in #2.

When I type:

```
:call SyntaxRange#Include('\$\$', '\$\$', 'tex', 'NonText')
```

Things work fine.

**Comment by CoderCookE** [comment]
2 Years late on this but, in case someone else runs into this issue like I did,  you need to make sure you install the [vim-ingo-library](https://github.com/inkarkat/vim-ingo-library)

**Comment by radraw** [comment]
> 2 Years late on this but, in case someone else runs into this issue like I did, you need to make sure you install the [vim-ingo-library](https://github.com/inkarkat/vim-ingo-library)

And yet 4 more years later I also run into this issue. Thank you for your helpful  comment. Maybe it would be good the need of installing the dependency library to be more highlighted in install instructions.
