### ISSUE TITLE
Working manually but not working with autocmd

### ISSUE THREAD

**Issue by HaleTom** [inkarkat/vim-SyntaxRange#5]
If I have a markdown file containing:

```
$$ \displaystyle a^{b}_c $$
```

and I type:

```
:call SyntaxRange#Include('\$\$', '\$\$', 'tex', 'NonText')
```

Then the line gets highlighted as expected.

However, if I have the same file with `.vimrc`:

```
autocmd FileType markdown call SyntaxRange#Include('\$\$', '\$\$', 'tex', 'NonText')
```

Then there is no highlighting.

I am using `vim-markdown` to highlight the surrounding markdown.

**Comment by HaleTom** [comment]
Hmm, I notice that the surrounding `$$` are correctly coloured in the `autocmd` case, but nothing inside.

**Comment by inkarkat** [comment]
Autocmds, especially around syntax highlighting, are very sensitive to the order in which they are run. Try typing `autocmd FileType markdown call SyntaxRange#Include(...)` _after_ launching Vim, but _before_ opening a Markdown file; that should work.

Maybe putting it at the end of your `.vimrc` will help; it definitely needs to be put after the usual `:filetype plugin on` command. If this is still causing problems, you need to look at the various `:autocmd`s that run (and their order), e.g. by `:set verbose=9`.

**Comment by radgeRayden** [comment]
I'm having a similar issue, if I change the buffer at all when I come back the foreign language is not highlighted anymore. I have this at the very end of my init.vim (neovim):
```vim
    autocmd Syntax * call SyntaxRange#Include('%foreign: C%', '%endf: C%', 'c', 'NonText')
    autocmd Syntax * call SyntaxRange#Include('%foreign: C++%', '%endf: C++%', 'cpp', 'NonText')
    autocmd Syntax * call SyntaxRange#Include('%foreign: lua%', '%endf: lua%', 'lua', 'NonText')
```
![image](https://user-images.githubusercontent.com/8618621/58462476-9d8c3600-80f7-11e9-81b7-7786ad9fa4a3.png)
as you can see only the delimiters are light up.
If I reopen neovim entirely, it looks like this:
![image](https://user-images.githubusercontent.com/8618621/58462513-b1d03300-80f7-11e9-8f83-bff84a4a21dd.png)

**Comment by inkarkat** [comment]
As I've mentioned, there are certain general complexities around syntax extensions; I'd need a minimal, reproducible example of the problem to see whether the plugin can offer any remediation here.
