### ISSUE TITLE
Highlighting stops working after `:e` to reload buffer

### ISSUE THREAD

**Issue by myitcv** [inkarkat/vim-SyntaxRange#7]
Thanks for this awesome plugin. Incredibly useful. 

I've found an issue when it comes to reloading a buffer, or more specifically when it comes to re-triggering `BufRead`. I'm totally stumped as to what is causing this so I thought I would raise an issue and see if some better Vim minds had any ideas.

Here is the repro:

```
cd $(mktemp -d) 
export HOME=$PWD
cat <<EOD > .vimrc
call plug#begin('~/.vim/plugged')
Plug 'inkarkat/vim-SyntaxRange'
call plug#end()

set nocompatible
set nobackup
set nowritebackup
set noswapfile

function s:SetupHighlights()
  hi Mine ctermfg=236 ctermbg=150 guifg=#303030 guibg=#afd787
  call SyntaxRange#IncludeEx('start="\%^" end="^\ze-- .* --$" containedin=ALL keepend', 'bash')
  let files = [
        \ [["markdown", "md"], "markdown"],
        \ [["go"], "go"],
        \ [["json"], "json"],
        \ [["sh", "bash"], "bash"],
        \]
  for f in files
    call SyntaxRange#IncludeEx('matchgroup=Mine start="^-- .*\.\('.join(f[0],'\|').'\)\(\.golden\)\? --$" end="^\ze-- .* --$" containedin=ALL keepend', f[1])
  endfor
  syn match Mine '^-- .* --$' containedin=ALL
  set commentstring=#%s
endfunction

autocmd BufNewFile,BufReadPost *.txt call s:SetupHighlights()
EOD

curl -sfLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
git clone https://github.com/inkarkat/vim-SyntaxRange .vim/plugged/vim-SyntaxRange
cat <<EOD > x.txt
echo $hello

-- test.json --
{
        "test": true
}
-- main.go --
package main

func main() {
        println("Hello")
}
EOD
```

Then `vim x.txt` and you will see some nice highlighting, like this:

<img width="420" alt="Screen Shot 2020-05-09 at 05 37 35" src="https://user-images.githubusercontent.com/3374574/81464209-5dfb1480-91b7-11ea-816e-9ece24b6cc31.png">
 
Now `:e` and then observe the region highlighting disappears:

<img width="411" alt="Screen Shot 2020-05-09 at 05 37 41" src="https://user-images.githubusercontent.com/3374574/81464208-5176bc00-91b7-11ea-80ed-912ec83a2e9e.png">

I haven't been able to track down via `set verbose=9` what's causing this.

Would be very grateful if anyone has any ideas!

**Comment by inkarkat** [comment]
Paul, thank you for the very precise reproduction steps and a very pleasant problem report overall!

The problem was caused by a re-inclusion guard introduced in version 1.03, causing a mismatch after a buffer reload between what the plugin thinks has been defined and what actually still is defined as syntax. I've tweaked the condition so that it will still prevent duplicate syntax inclusions in most cases, but now should handle buffer reloads and similar situations.

I'm glad you like the plugin; thanks for the feedback and happy Vimming!
