### ISSUE TITLE
How to leverage this for HSX

### ISSUE THREAD

**Issue by C-alcium** [inkarkat/vim-SyntaxRange#9]
Hi there, would you happen to know how I can leverage this plugin to achieve HSX highlighting support? 

Issuing the command 

`:call SyntaxRange#include('[hsx|', '|]', 'haskell', 'NonText')`

throws up an error stating that I did not include enough arguments. you can find HSX here, it's essentially JSX but for haskell: https://ihp.digitallyinduced.com/Guide/hsx.html 

Starts with: `[hsx|`
Ends with:  `|]`

Only inside of `.hs` (Haskell) files.

and ideally it would highlight the region as HTML

Any help would be much appreciated.

**Comment by inkarkat** [comment]
The first two arguments of `SyntaxRange#Include()` are regular expressions, but as you did not escape the `[` and `]` characters, Vim parses the entire resulting `start="[hsx" end="|]"` expression as one argument, and then (a bit misleadingly) complains about the missing (`end=...`) argument. So you either need to put `\V` in front of each pattern to make it "very nomagic", or simply escape the character as `\[`.

If I understand the syntax correctly, this is HTML embedded inside Haskell. So the third argument would be `html`. (If you have a syntax for that "blaze HTML" dialect, that would be even better.)

So the call should look like this:

    call SyntaxRange#Include('\[hsx|', '|\]', 'html', 'NonText')

To apply this automatically for the `haskell` filetype, put it into a script in `~/.vim/after/syntax/haskell/SyntaxInclude.vim`.
